telegram_token: ""
openai_api_key: ""
allowed_telegram_usernames: []  # if empty, the bot is available to anyone
persistence_path: "./persistence.pkl"  # path where to store user data
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)